# ═══════════════════════════════════════════════════════════════════════
# AGENT CONFIGURATION FILE
# Describes robot kinematics, joints, actuators, initial state
# ═══════════════════════════════════════════════════════════════════════

# ─────────────────────────────────────────────
# Metadata
# ─────────────────────────────────────────────
name: exomy
version: 0
robot_model_path: /exomy/exomy.usd
controller_config: ackermann

# ─────────────────────────────────────────────
# Controller Parameters
# ─────────────────────────────────────────────
controller:
     asset_name: robot                           # Asset name (No reason to change)
     wheelbase_length: 0.29778                     # [meters] Distance between front & rear wheels
     middle_wheel_distance: 0.1548                # [meters] Distance between middle wheels
     rear_and_front_wheel_distance: 0.1548         # [meters] Distance between front & rear wheels
     wheel_radius: 0.1                           # [meters] Wheel radius
     min_steering_radius: 0.4                    # [meters] Minimum turning radius
     steering_joint_names: ["FL_Steer_Joint", "RL_Steer_Joint", "RR_Steer_Joint", "FR_Steer_Joint"]  # Steering joints (regex supported)
     drive_joint_names: [".*Drive_Joint"]   # Drive joints (regex supported)
     offset: 0.0                             # Default: 0.0
     scale: [1.0, 1.0]                           # Default: [0.0, 0.0]
     steering_order: ["FL", "FR", "RL", "RR"]    # Steering joint order
     drive_order: ["FL", "FR", "CL", "CR", "RL", "RR"] # Drive joint order]

# ─────────────────────────────────────────────
# Joint Actuator Configuration
# ─────────────────────────────────────────────
joints:
    base_drive:
      joint_names_expr: [".*Drive_Joint"]
      velocity_limit: 6
      effort_limit: 12
      stiffness: 100.0
      damping: 4000.0
    base_steering:
      joint_names_expr: [".*Steer_Joint"]
      velocity_limit: 6
      effort_limit: 12
      stiffness: 8000.0
      damping: 1000.0
    passive_joints:
      joint_names_expr: [".*Bogie_Joint"]
      velocity_limit: 15
      effort_limit: 0
      stiffness: 0.0
      damping: 0.0

# ─────────────────────────────────────────────
# Physics Properties
# ─────────────────────────────────────────────
collision_properties:
    contact_offset: 0.04
    rest_offset: 0.01
rigidBody_properties:
    max_linear_velocity: 1.5
    max_angular_velocity: 1000.0
    max_depenetration_velocity: 1.0
    disable_gravity: false
simulation_properties:
    self_collision: false
    solver_position_iteration_count: 32
    solver_velocity_iteration_count: 4

# ─────────────────────────────────────────────
# Initial Pose Configuration
# ─────────────────────────────────────────────
pose_config:
    init_pose: [0.0, 0.0, 0.0]
    joint_pose:
      pose_config:
        names: [".*Steer_Joint"]
        values: [0.0]
      velocity_config:
        names: [".*Steer_Joint", ".*Drive_Joint"]
        values: [0.0, 0.0]
