# ═══════════════════════════════════════════════════════════════════════
# AGENT CONFIGURATION FILE
# Describes robot kinematics, joints, actuators, initial state
# ═══════════════════════════════════════════════════════════════════════

# ─────────────────────────────────────────────
# Metadata
# ─────────────────────────────────────────────
name: summit_xl
version: 0
robot_model_path: /summit_xl/summit_xl.usd
controller_config: skidsteer

# ─────────────────────────────────────────────
# Controller Parameters
# ─────────────────────────────────────────────
controller:
    asset_name: robot
    scale: [6.0, 6.0]                  # Default: [1.0, 1.0]
    offset: 0.0                       # Default: 0.0
    track_width: 0.470                 # [meters] Distance between left & right wheels
    wheel_radius: 0.1175               # [meters] Wheel radius
    drive_joint_names: [".*Drive_Joint"]# Names of wheel joints (regex supported)

# ─────────────────────────────────────────────
# Joint Actuator Configuration
# ─────────────────────────────────────────────
joints:
  base_drive:
      joint_names_expr: [".*Drive_Joint"]
      velocity_limit: 10
      effort_limit: 100
      stiffness: 2.0
      damping: 25.0
# ─────────────────────────────────────────────
# Physics Properties
# ─────────────────────────────────────────────
collision_properties:
    contact_offset: 0.04
    rest_offset: 0.01
rigidBody_properties:
    max_linear_velocity: 3
    max_angular_velocity: 60.0
    max_depenetration_velocity: 1.0
    disable_gravity: false
simulation_properties:
    self_collision: false
    solver_position_iteration_count: 32
    solver_velocity_iteration_count: 4

# ─────────────────────────────────────────────
# Initial Pose Configuration
# ─────────────────────────────────────────────
pose_config:
    init_pose: [0.0, 0.0, 0.0]
    joint_pose:
      velocity_config:
        names: [".*Drive_Joint"]
        values: [0.0, 0.0]