# ═══════════════════════════════════════════════════════════════════════
# AGENT CONFIGURATION FILE
# Describes robot kinematics, joints, actuators, initial state
# ═══════════════════════════════════════════════════════════════════════

# ─────────────────────────────────────────────
# Metadata
# ─────────────────────────────────────────────
name: leo_rover
version: 0
robot_model_path: /leo_rover/leo_rover.usd
controller_config: skidsteer

# ─────────────────────────────────────────────
# Controller Parameters
# ─────────────────────────────────────────────
controller:
  asset_name: robot
  track_width: 0.359
  wheel_radius: 0.065
  drive_joint_names: [".*Drive_Joint"]
  drive_order: ["FL", "RL", "FR", "RR"]
  drive_id_override: [2, 3, 4, 5]
  offset: 0.0
  scale: [3.0, 3.0]

# ─────────────────────────────────────────────
# Joint Actuator Configuration
# ─────────────────────────────────────────────
joints:
    base_drive:
      joint_names_expr: [".*Drive_Joint"]
      velocity_limit: 6
      effort_limit: 20
      stiffness: 1.0
      damping: 15.0

# ─────────────────────────────────────────────
# Physics Properties
# ─────────────────────────────────────────────
collision_properties:
    contact_offset: 0.04
    rest_offset: 0.01
rigidBody_properties:
    max_linear_velocity: 3
    max_angular_velocity: 60.0
    max_depenetration_velocity: 1.0
    disable_gravity: false
simulation_properties:
    self_collision: false
    solver_position_iteration_count: 32
    solver_velocity_iteration_count: 4

# ─────────────────────────────────────────────
# Initial Pose Configuration
# ─────────────────────────────────────────────
pose_config:
    init_pose: [0.0, 0.0, 0.0]
    joint_pose:
      pose_config:
        names: [".*Bogie_Joint"]
        values: [0.0]
      velocity_config:
        names: [".*Drive_Joint", ".*Bogie_Joint"]
        values: [0.0, 0.0]
