---
name: roburoc,
robot_model_path: /roburoc_simple/roburoc.usd, # relative path to robots folder e.g. /aau_rover/Mars_Rover.usd
controller_config: skidsteer,
controller:
  {
    scale: [1.0, 1.0],
    offset: [0.0, 0.0],
    track_width: 0.470,
    wheel_radius: 0.1175,
    drive_joint_names: [".*Drive_Joint"]
  }
joints:
  {
    base_drive:
    {
      joint_names_expr: [".*Drive_Joint"],
      velocity_limit: 6,
      effort_limit: 12,
      stiffness: 100.0,
      damping: 4000.0
    },
    passive_joints:
    {
      joint_names_expr: [".*Bogie_Joint"],
      velocity_limit: 10,
      effort_limit: 0,
      stiffness: 0.0,
      damping: 0.0,
    }
  }
collision_properties:
  {
    contact_offset: 0.04,
    rest_offset: 0.01
  }
rigidBody_properties:
  {
    max_linear_velocity: 3,
    max_angular_velocity: 60.0,
    max_depenetration_velocity: 1.0,
    disable_gravity: false,
  }
simulation_properties:
  {
    self_collision: false,
    solver_position_iteration_count: 32,
    solver_velocity_iteration_count: 4,
  }
pose_config:
  {
    init_pose: [0.0, 0.0, 0.0],
    joint_pose:
    {
      pose_config:
      {
        names: [".*Steer_Revolute"],
        values: [0.0]
      },
      velocity_config:
      {
        names: [".*Steer_Revolute", ".*Drive_Continous"],
        values: [0.0, 0.0]
      }
    }
  }
