---
terrain:
{
  obstacles:
  {
    no_obstacles: "False"
  },
  physics:
  {
    enable_stabilization: "True",
    friction_correlation_distance: "0.025"
    gpu:
    {
      gpu_max_rigid_contact_count: "8388608",
      gpu_max_rigid_patch_count: "262144",
      gpu_found_lost_pairs_capacity: "2**21",
      gpu_found_lost_aggregate_pairs_capacity: "2**25",  # 2**21,
      gpu_total_aggregate_pairs_capacity: "2**21",   # 2**13,
      gpu_max_soft_body_contacts: "1048576",
      gpu_max_particle_contacts: "1048576",
      gpu_heap_capacity: "67108864",
      gpu_temp_buffer_capacity: "16777216",
      gpu_max_num_partitions: "8",
      gpu_collision_stack_size: "2**28",
    }
  },
}