# ═══════════════════════════════════════════════════════════════════════
# AGENT CONFIGURATION FILE
# Describes robot kinematics, joints, actuators, initial state
# ═══════════════════════════════════════════════════════════════════════

# ─────────────────────────────────────────────
# Metadata
# ─────────────────────────────────────────────
name: roburoc_simple
version: 0
robot_model_path: /RobuROC4_Simple/RobuROC4_Simple.usd
controller_config: skidsteer

# ─────────────────────────────────────────────
# Controller Parameters
# ─────────────────────────────────────────────
controller:
    asset_name: robot
    scale: [1.0, 2.0]                  # Default: [1.0, 1.0]
    offset: 0.0                        # Default: 0.0
    track_width: 0.690                 # [meters] Distance between left & right wheels
    wheel_radius: 0.290                # [meters] Wheel radius
    drive_joint_names: [".*Drive_Joint"]# Names of wheel joints (regex supported)
    drive_order: ["FL", "FR", "RL", "RR"]

# ─────────────────────────────────────────────
# Joint Actuator Configuration
# ─────────────────────────────────────────────
joints:
    base_drive:
      joint_names_expr: [".*Drive_Joint"]
      velocity_limit: 4
      effort_limit: 1000
      stiffness: 25.0
      damping: 275.0

# ─────────────────────────────────────────────
# Physics Properties
# ─────────────────────────────────────────────
collision_properties: # Properties related to collision with the robot
    contact_offset: 0.05                       # [meters] Offset considered contact with other object
    rest_offset: 0.01                           # [meters] Offset considered rest at contact with object
rigidBody_properties: # Properties of the rigid body
    max_linear_velocity: 2.0                   # [m/s]
    max_angular_velocity: 60.0                  # [rad/s]
    max_depenetration_velocity: 1.0            # [m/s] makes collision response slower
    disable_gravity: False                     # [Bool] whether to disable gravity for the body
simulation_properties: # Simulation properties
    self_collision: False                      # Allow collision of the individual parts of the robot
    solver_position_iteration_count: 32        # Number of iterations when solving for position
    solver_velocity_iteration_count: 4         # Number of iterations when solving for velocity

# ─────────────────────────────────────────────
# Initial Pose Configuration
# ─────────────────────────────────────────────
pose_config:
    init_pose: [0.0, 0.0, 0.0]               # [m] Initial pose
    joint_pose: # initial joint poses
      velocity_config: # Velocity
        names: [".*Drive_Joint"] # Names of joints
        values: [0.0, 0.0]                      # and their initial velocities
